# -*- coding: utf-8 -*-
"""HACKATHON_NIT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXQOqgLbARBIQXBCoqrEdCc7ZPN7xcLE
"""

import urllib
data=urllib.request.urlopen("https://api.thingspeak.com/channels/2030468/fields/2.json?results=2") 
print(data.read())

d=308.97501 #m
v=0
u=25 #90 kmph
a=((v**2)-(u**2))/(2*d)
print("The deceleration is",a,"m/s^2")

acc=2.8
velocity=0
enginestatus=1


if acc>1.4705:
  print("Warning! Optimal acceleration limit exceeded")
if velocity<80 or velocity>100:
  print("Warning! Out of optimal speed range")
if enginestatus==1 and velocity==0:
  print("Warning! Engine IDLE")